include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    sort_pub_dependencies: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
